service: gainesvilletips

provider:
  name: aws
  runtime: python3.8

functions:
  webapi:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: gainesvilletips_org.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
